### ISSUE TITLE
[fix]: tree.messages set to undefined after posthtml-beautify done processing

### ISSUE THREAD

**Issue by andreyvolokitin** [GitScrum/posthtml-beautify#211]
In ```posthtml.config.js```  I have multiple plugins, which set [```tree.messages```](https://github.com/posthtml/posthtml/blob/7ff3f9b3c4aef5c7f25ed4cd0b07d15ee44544f0/lib/api.js#L87) API property for later [usage](https://github.com/posthtml/posthtml-loader/blob/master/lib/index.js#L117) by ```posthtml-loader```. I also have ```posthtml-beautify``` as a last plugin declared in ```posthtml.config.js```. 

```tree.messages``` has proper value if there is no  ```posthtml-beautify``` declared in config, but it has ```undefined``` value if I declare ```posthtml-beautify``` in a config (I test this value by checking ```result.messages```  in a ```posthtml-loader``` on [this line](https://github.com/posthtml/posthtml-loader/blob/master/lib/index.js#L117)). So ```posthtml-beautify``` somehow interferes with this property, but from the source I yet can not find how exactly

**Comment by andreyvolokitin** [comment]
@GitScrum, were you able to reproduce? Is example still needed?

**Comment by GitScrum** [comment]
@andreyvolokitin no, thanks, i know what the problem is

**Comment by GitScrum** [comment]
@andreyvolokitin now is good

**Comment by andreyvolokitin** [comment]
Something is wrong, now invocation of ```require('posthtml-beautify')``` in the ```posthtml.config.js``` (https://i.imgur.com/09wDYJm.png) causing this error: 
```
TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/posthtml.config.js:12:33)
```

**Comment by GitScrum** [comment]
@andreyvolokitin everything should work see my [demo](https://github.com/GitScrum/posthtml-beautify/blob/master/src/docs/app.js#L13)

put your example on the githab and I'll see what's wrong

**Comment by andreyvolokitin** [comment]
See here: https://github.com/andreyvolokitin/posthtml-beautify-test. It has something to do with ```cosmiconfig``` and probably with ```posthtml-load-config```. 

-------
BTW ```posthtml-beautify``` causes this error if I have no ```babel-core``` installed as the main dev dependency:
```bash
{ Error: Cannot find module 'babel-runtime/core-js/promise'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andreyvolokitin/posthtml-beautify-test/node_modules/posthtml-beautify/lib/index.js:1:89)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andreyvolokitin/posthtml-beautify-test/posthtml.config.js:3:7)
    at Module._compile (module.js:641:30)
    at requireFromString (/Users/andreyvolokitin/posthtml-beautify-test/node_modules/require-from-string/index.js:27:4)
    at /Users/andreyvolokitin/posthtml-beautify-test/node_modules/cosmiconfig/lib/loadJs.js:11:15
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

**Comment by GitScrum** [comment]
moved to #213

**Comment by andreyvolokitin** [comment]
Operating System: OS X 10.11.6
Node Version: 9.2.1
NPM Version: 5.6.0

**Comment by GitScrum** [comment]
https://github.com/andreyvolokitin/posthtml-beautify-test now returns `<div></div>` ((

**Comment by andreyvolokitin** [comment]
I used to encounter the same output (on other occasions) while using non-require (simple strings) notation for defining plugins in ```posthtml.config.js```, see https://github.com/posthtml/posthtml-loader/issues/118. But with defining plugin like that: ```require('posthtml-beautify')({})``` — in this example on my machine it just throws an error in the console:
```bash
TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/posthtml.config.js:3:35)
    at Module._compile (module.js:641:30)
    at requireFromString (/Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/require-from-string/index.js:27:4)
    at /Users/andreyvolokitin/webdev/sandbox/posthtml-beautify-test/node_modules/cosmiconfig/lib/loadJs.js:11:15
    at <anonymous>
Hash: 98c103f155489fad7cd1
```

**Comment by andreyvolokitin** [comment]
It is like ```cosmiconfig``` or ```posthtml-load-config``` can't ```require``` ```posthtml-beautify``` anymore

**Comment by andreyvolokitin** [comment]
So looking at the error stack trace:
```bash
TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/posthtml.config.js:24:33)
    at Module._compile (module.js:641:30)
    at requireFromString (/Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml-load-config/node_modules/require-from-string/index.js:29:4)
    at /Users/andreyvolokitin/webdev/sandbox/frontend-stub/node_modules/posthtml-load-config/node_modules/cosmiconfig/lib/loadJs.js:11:15
    at <anonymous>
```
it says that the thing returned by ```require('posthtml-beautify')``` in my config — is not a function, but I am trying to call it like usual with ```require``` plugin notation: ```require('posthtml-beautify')({})```. Could this mean that ```posthtml-beautify``` after v0.1.8 started to export not a function, but something else? Because in v0.1.8 this notation worked, meaning that ```require('posthtml-beautify')``` returned function back then. That is what was changed in the export code: https://github.com/GitScrum/posthtml-beautify/commit/bba14e27a308dfac2d31784c19d610ca711100da#diff-1fdf421c05c1140f6d71444ea2b27638R245. I assume this is what caused this error
